services:
  redis:
    image: redis:6.2.5
    env_file: ./docker.env
    container_name: redis
    networks:
      - outline-network
    command: ["redis-server"]
  postgres:
    image: postgres:15.3
    container_name: outline_postgres
    env_file: ./docker.env
    networks:
      - outline-network
    volumes:
      - outline-postgres:/var/lib/postgresql/data
  outline:
    image: mislavperi/outline
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./docker.env
    container_name: outline
    volumes:
      - storage-data:/var/lib/outline/data
    networks:
      - outline-network
      - reverse-proxy
    depends_on:
      - postgres
      - redis
    ports:
      - 127.0.0.1:3011:3000

networks:
  outline-network:
    name: outline-network
    external: true
  reverse-proxy:
    external: true
volumes:
  outline-postgres:
  storage-data:
