services:
  redis:
    image: redis:6.2.5
    env_file: ./docker.env
    container_name: redis
    ports:
      - 6378:6379
    networks:
      - outline-network
    command: ["redis-server"]
  postgres:
    image: postgres:15.3
    container_name: outline_postgres
    env_file: ./docker.env
    networks:
      - outline-network
    volumes:
      - outline-postgres:/var/lib/postgresql/data
  outline:
    image: mislavperi/outline
    build:
      context: .
      image: Dockerfile
    env_file: ./docker.env
    container_name: outline
    volumes:
      - storage-data:/var/lib/outline/data
    networks:
      - outline-network
    depends_on:
      - postgres
      - redis
    ports:
      - 3011:3000

networks:
  outline-network:
    external: true

volumes:
  outline-postgres:
  storage-data:
