services:
  outline:
    image: mislavperi/outline
    build: ./Dockerfile
    env_file: ./docker.env
    container_name: outline
    volumes:
      - storage-data:/var/lib/outline/data
    networks:
      - outline-network
    depends_on:
      - outline_postgres
      - redis
    ports:
      - 3011:3000
  redis:
    image: redis
    env_file: ./docker.env
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - outline-network
    command: ["redis-server"]
  postgres:
    container_name: outline_postgres
    env_file: ./docker.env
    networks:
      - outline-network
    volumes:
      - outline-postgres:/var/lib/postgresql/data

networks:
  outline-network:
    external: true
